language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get github.com/golang/lint/golint

before_script:
  - go vet ./...
  - golint ./...

script:
  - go test -v ./pkg/moq
